### ISSUE TITLE
Could you please give some clues of how to get the spherical image in your paper?

### ISSUE THREAD

**Issue by zhixuanli** [daniilidis-group/spherical-cnn#1]
Could you please give some clue of how to get the spherical image in your paper?
Just like Figure 1 and 3.
These figures are amazing, but I can't find how to visualize them after reading your codes.

Could you give me some clues?
Thank you so much!

**Comment by machc** [comment]
Hi, thanks for your interest. 

I use [Mayavi](http://docs.enthought.com/mayavi/mayavi/) to plot the spherical images. Something like this
```python 
from mayavi import mlab
mlab.mesh(x, y, z, scalars=f, colormap='coolwarm')
```
where x, y, z are the 3D coordinates of points on the spherical surface and f is the spherical image.

**Comment by zhixuanli** [comment]
@machc It's very useful!! Thank you so much! 

[Spherical harmonics example](https://stackoverflow.com/questions/23517416/colors-on-a-sphere-to-depict-values)

The above link maybe helpful to the others looking at this issue.

**Comment by lixiang-ucas** [comment]
@zhixuanli  Thanks a lot.

**Comment by AnranQi** [comment]
@machc May I ask whether f in 'scalars=f' is the distance/angle of the 3D model (i.e. the input of the network)?  And x,y,z are 
  x =  cos(latitude) * cos(longitude)
  y =  cos(latitude) * sin(longitude)
  z =  sin(latitude)?

I tried like this but got a strange photo.

Thanks for help.

**Comment by machc** [comment]
Yes, this looks correct. The distance channel is easy to interpret, the angles not so much. Note that latitudes are columns in our representation so you may have to transpose f.

**Comment by AnranQi** [comment]
@machc Thanks, Carlos. 

I am re-implementing your follow-up paper Cross-Domain 3D Equivariant Image Embeddings and could you please help to answer a few questions pertaining to view synthesis?

1) Does target spherical embedding the concatenate of distance branch feature map and angle branch feature map at resolution 32 * 32?

2) Do you apply WGAP/ magnitude per degree of the SFT coefficients to the target spherical embedding? If not how to make different rotation but same identity 3D object has the same spherical embedding?

3) How many channels per layer for that 10 spherical convolutional layers? Previously, it is [16 16 32 32 64 64 128 128] for 8 layers.

4) Does the synthesizer network have the same network structure with encoder-decoder which learns the transformation to the target spherical embedding?

Thanks a lot for help.

**Comment by machc** [comment]
@AnranQi sorry I missed your message!
1) We use only the distance branch for that paper, see supplementary material of the camera ready version here for details: https://arxiv.org/abs/1812.02716. 
2) We don't use global pooling on the embeddings because we want them to live on the sphere, so rotated versions of the same object have embeddings related by the same rotation.
3, 4) Please see the camera-ready supplementary material for full details about the architecture.
