### ISSUE TITLE
how to get the input for this model?

### ISSUE THREAD

**Issue by lixiang-ucas** [daniilidis-group/spherical-cnn#2]
Hello, @machc , how you get the (None,64,64,2) input for this spherical-cnn model? e.g., a point cloud with (N,3) coordinates as an input.

**Comment by machc** [comment]
Hi, our inputs are meshes, not point clouds. The procedure to produce spherical images from meshes is in section 5.1 of the paper, and it also works for voxel grids. You can find the processed dataset [here](https://drive.google.com/file/d/1_yJCn0lWkb8gvaHxwTTkGlLVT8dKR0Hc/view?usp=sharing).

If you want to work with point clouds, one straightforward way is to assign the average distance to points within an spherical sector to the spherical function value at that sector.

**Comment by lixiang-ucas** [comment]
Nice work! Thanks for your suggestion.
