### ISSUE TITLE
Provide z/SO(3) data for ModelNet40

### ISSUE THREAD

**Issue by lxxue** [daniilidis-group/spherical-cnn#4]
Thanks for releasing the code. 

It seems that the provided dataset is SO(3)/z. I wonder if you can provide the z/SO(3) dataset?

**Comment by lxxue** [comment]
or if you could provide the original spherical representation without data augmentation? I'd like to split the dataset and do the data augmentation using sphrot_shtools functions.

**Comment by machc** [comment]
Hi, thanks for your interest. I have uploaded the 'z' version of the dataset here, augmented with azimuthal rotations only: https://drive.google.com/file/d/1yyG9bT3B8gK_7XBL0dqxxZs4I7UZWN__

I don't have tfrecords for the canonical orientations. What you can do is start from a single tfrecord (train0.tfrecord, for example), and augment from there. Each training tfrecord contains a single copy of every training instance, at a random azimuth.

**Comment by lxxue** [comment]
Thanks for the suggestion. I should have noticed that. 

Sorry to bother again, is there any way that I can get the test data without augmentation?
