### ISSUE TITLE
query for equirectangular images

### ISSUE THREAD

**Issue by ustundag** [daniilidis-group/spherical-cnn#7]
Hi all, thanks for your great effort in this research!

I have a question on how to get the feature map of an equirectangular image input? Dear sir @machc, Can you please share your precious comments?

**Comment by machc** [comment]
Hi, thanks for your interest! Please take look at the function `get_tfrecord_activations` [here](https://github.com/daniilidis-group/spherical-cnn/blob/31a375ba4c3580bcf87f691e6c8c99f0ab56d3c4/spherical_cnn/models.py#L484). It returns the activations at any layer given a model and a tfrecord input.
