### ISSUE TITLE
Code for shape alignment and equvariance error

### ISSUE THREAD

**Issue by yongheng1991** [daniilidis-group/spherical-cnn#8]
Hi, 
Recently we are working on the related topic. We found your work very inspiring. 
Could you also provide your code for the shape alignment and equivariance error?
I found the function in your code with which I can get activations per layer. But it would be better if you can offer the code to calculate the relative pose error with the correlation in the shape alignment. 
Also, it would be better if you can offer the code to calculate the pointwise relative error in the equivariance error experiment. Thanks.
Besides, I can only get the rotation ID in the dataset you provided. Could you also provide the corresponding rotation matrix? 
Best regards

**Comment by machc** [comment]
This was resolved via email. I'll post some of the info here so it may help others.

For shape alignment, please look at the matlab files here: https://github.com/machc/spherical_embeddings and the dependencies on the libraries: https://home.cs.dartmouth.edu/~geelong/soft/ and https://home.cs.dartmouth.edu/~geelong/sphere libraries. The process I used to produce the results in the paper is very tedious: use python to save feature maps, convert to matlab, run the spherical correlations using the Dartmouth libraries and compute errors.

Regarding rotation id, we only need the rotation matrix in the shape alignment experiment, which is performed only in 4 categories in the ModelNet test set. Here's the dataset we used: https://drive.google.com/drive/folders/1H2RNJb4JCWDQjpQGYW43A_6r76yL4F7j?usp=sharing
The file meta.npz contains the rotations for each entry.
